"""Add size, description, orbit_period to moon

Revision ID: 0a669c3dfe71
Revises: f3802ea72987
Create Date: 2025-05-06 12:35:44.152822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a669c3dfe71'
down_revision = 'f3802ea72987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('orbit_period', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('orbit_period')
        batch_op.drop_column('description')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
